export const COMMON_PATTERNS = [
  "# Common Patterns",
  "",
  "## Research & Document",
  "",
  "Extract content from a page and save it as a document:",
  "```javascript",
  "const content = await browserjs(() => ({",
  "  title: document.title,",
  "  text: document.body.innerText.substring(0, 5000),",
  "}));",
  "await returnFile('research.md', `# ${content.title}\\n\\n${content.text}`, 'text/markdown');",
  "```",
  "",
  "## Multi-page Scraping (SPA / CSR sites)",
  "",
  "Collect data across multiple pages that need JS rendering (use `navigate` + `browserjs`):",
  "```javascript",
  "const allItems = [];",
  "for (let page = 1; page <= 5; page++) {",
  "  await navigate(`https://site.com/list?page=${page}`);",
  "  const items = await browserjs(() =>",
  "    Array.from(document.querySelectorAll('.item')).map(el => ({",
  "      name: el.querySelector('h2')?.textContent,",
  "      price: el.querySelector('.price')?.textContent,",
  "    }))",
  "  );",
  "  allItems.push(...items);",
  "}",
  "await createOrUpdateArtifact('items.json', allItems);",
  "```",
  "",
  "<!-- BG_FETCH_SECTION_START -->",
  "## Multi-URL Fetch (static / server-rendered pages, JSON APIs)",
  "",
  "複数の静的 / server-rendered ページを 1 回の `repl` で集めるときは `bgFetch()` を loop し、結果を artifact に保存する。詳しい使い分けは top-level `bg_fetch` tool description を参照。",
  "<!-- BG_FETCH_SECTION_END -->",
  "",
  "**Data storage rule:** `createOrUpdateArtifact` for structured JSON data (name with `.json` extension). `returnFile` for user-facing files (HTML, CSV, Markdown, images).",
  "",
  "## Data Processing",
  "",
  "Extract, transform, and save data:",
  "```javascript",
  "// 1. Extract",
  "const raw = await browserjs((sel) =>",
  "  Array.from(document.querySelectorAll(sel)).map(el => ({",
  "    title: el.querySelector('.title')?.textContent?.trim(),",
  "    price: el.querySelector('.price')?.textContent?.trim(),",
  "  })),",
  "'.product'",
  ");",
  "",
  "// 2. Transform",
  "const processed = raw.filter(item => item.title && item.price);",
  "",
  "// 3. Save",
  "const csv = ['name,price', ...processed.map(i => `${i.title},${i.price}`)].join('\\n');",
  "await returnFile('products.csv', csv, 'text/csv');",
  "```",
  "",
  "## Interactive Dashboard",
  "",
  "Generate an HTML dashboard from scraped data:",
  "```javascript",
  "const data = await getArtifact('items');",
  "const rows = data.map(i => `<tr><td>${i.name}</td><td>${i.price}</td></tr>`).join('');",
  "const html = `<!DOCTYPE html>",
  "<html><head><title>Dashboard</title></head>",
  "<body><table><thead><tr><th>Name</th><th>Price</th></tr></thead>",
  "<tbody>${rows}</tbody></table></body></html>`;",
  "await returnFile('dashboard.html', html, 'text/html');",
  "```",
  "",
  "## Website Automation",
  "",
  "Fill forms and navigate workflows:",
  "```javascript",
  "// Login flow",
  "await navigate('https://site.com/login');",
  "await nativeType('input[name=\"email\"]', 'user@example.com');",
  "await nativeType('input[name=\"password\"]', 'secret');",
  "await nativeClick('button[type=\"submit\"]');",
  "",
  "// Wait for redirect",
  "let attempts = 0;",
  "while (attempts < 10) {",
  "  const onDashboard = await browserjs(() => location.pathname.includes('/dashboard'));",
  "  if (onDashboard) break;",
  "  await new Promise(r => setTimeout(r, 500));",
  "  attempts++;",
  "}",
  "```",
  "",
  "## Form Submission That Doesn't Work",
  "",
  "If clicking the submit button doesn't submit the form:",
  "1. Check if all required fields are filled",
  "2. Try pressing Enter after the last field: `await nativePress('Enter')`",
  "3. Some forms need explicit button click: `await nativeClick('button[type=\"submit\"]')`",
  "",
  "## Waiting for Page Updates",
  "",
  "After clicking or typing, the page might update dynamically. Use browserjs() to poll for changes:",
  "```javascript",
  "let attempts = 0;",
  "while (attempts < 10) {",
  "  const exists = await browserjs((sel) => document.querySelector(sel) !== null, '.result');",
  "  if (exists) break;",
  "  await new Promise(r => setTimeout(r, 500));",
  "  attempts++;",
  "}",
  "```",
  "",
  "## Element Not Found",
  "",
  'If nativeClick() or nativeType() fails with "Element not found":',
  "1. Use browserjs() to verify the selector",
  "2. Try alternative selectors (class, ID, attribute)",
  "3. If inside an iframe, you cannot access it — tell the user",
  "4. If lazy-loaded, scroll first with nativeScroll()",
].join("\n");

export const AVAILABLE_FUNCTIONS = [
  "# Available Functions",
  "",
  "## REPL Persistence Model (read this first)",
  "",
  "- Variables declared in one `repl` call do **NOT** survive to the next call. Each call starts from a fresh scope.",
  "- For multi-step workflows, save intermediate state via `createOrUpdateArtifact(name, data)` and read it back with `getArtifact(name)` in a later call.",
  "- Anti-pattern: calling `repl` multiple times merely to re-verify or re-inspect data you already retrieved. Previous tool results remain visible to you at full length in the conversation history — trust them.",
  "",
  "## Skills (Check First)",
  "",
  "Check `skills` before writing custom DOM code. If a site skill already covers the workflow, use it instead of re-implementing extraction or interaction logic.",
  "",
  "## Native Input Functions (REQUIRED for interactions)",
  "",
  "Chrome debugger 経由で trusted な入力イベントを発火する。通常 DOM 操作で動かない bot 対策ページではこれを使う。",
  "",
  "- `nativeClick(selector, options?)`",
  "- `nativeDoubleClick(selector)`",
  "- `nativeRightClick(selector)`",
  "- `nativeHover(selector)`",
  "- `nativeType(selector, text)`",
  "- `nativePress(key)`",
  "- `nativeKeyDown(key)`",
  "- `nativeKeyUp(key)`",
  "- `nativeFocus(selector)`",
  "- `nativeBlur(selector?)`",
  "- `nativeScroll(selector, options?)`",
  "- `nativeSelectText(selector, start?, end?)`",
  "",
  "## Function Summary",
  "",
  "| Function | Purpose |",
  "| --- | --- |",
  "| `browserjs(fn, ...args)` | Read/scrape JSON-serializable data from the active page context. |",
  "| `navigate(url)` | Navigate to another page and wait for load before the next extraction step. |",
  "<!-- BG_FETCH_SECTION_START -->",
  "| `bgFetch(url, options?)` | Fetch static/server-rendered pages or APIs outside the page context. 詳しい使い分けは top-level `bg_fetch` tool description を参照。 |",
  "<!-- BG_FETCH_SECTION_END -->",
  "| `createOrUpdateArtifact(name, data)` | Save JSON-serializable data for later REPL calls. |",
  "| `getArtifact(name)` | Read previously saved artifact data. |",
  "| `listArtifacts()` | List stored artifact names. |",
  "| `deleteArtifact(name)` | Delete a stored artifact. |",
  "| `returnFile(name, content, mimeType)` | Deliver a generated file to the user / Artifact Panel. |",
  "",
  // NOTE: skill-draft ツールと artifacts ツールの詳細は各 top-level ツールの
  // description に保持する。ここ（AVAILABLE_FUNCTIONS）は REPL 内から使える
  // 関数に限定して重複を避ける。
].join("\n");

export type ReplDescriptionSectionKey = "COMMON_PATTERNS" | "AVAILABLE_FUNCTIONS";

const SECTIONS: Record<ReplDescriptionSectionKey, string> = {
  COMMON_PATTERNS,
  AVAILABLE_FUNCTIONS,
};

// bgFetch 関連の部分は <!-- BG_FETCH_SECTION_START --> / <!-- BG_FETCH_SECTION_END -->
// で囲んである。enableBgFetch=false の時はマーカごと中身を削除し、AI から
// bgFetch の存在を隠す。true の時はマーカ行だけ取り除いて中身を残す。
//
// 同じマーカは system-prompt-v2 経由の prompt でも使われるため、本ヘルパは
// 両パスから再利用する。どちらの値でも sentinel 文字列自体は必ず取り除く。
const BG_FETCH_SECTION_RE = /^<!-- BG_FETCH_SECTION_START -->\n([\s\S]*?)^<!-- BG_FETCH_SECTION_END -->\n?/gm;

export function stripBgFetchSections(text: string, enableBgFetch: boolean): string {
  if (enableBgFetch) {
    return text.replace(BG_FETCH_SECTION_RE, (_match, body: string) => body);
  }
  return text.replace(BG_FETCH_SECTION_RE, "");
}

export function assembleReplDescriptionSections(
  keys: ReplDescriptionSectionKey[],
  options: { enableBgFetch?: boolean } = {},
): string {
  const joined = keys.map((key) => SECTIONS[key]).join("\n\n");
  return stripBgFetchSections(joined, options.enableBgFetch ?? true);
}
