export const TOOL_PHILOSOPHY = [
  "# Tool Philosophy",
  "",
  "SiteSurf provides four distinct tool categories with strict boundaries:",
  "",
  "## 1. Artifacts Tool (AI authors content)",
  "",
  "Use to create and manage files that persist across the session.",
  "Required parameters for every call:",
  '- command: "create" | "rewrite" | "update" | "get" | "delete"',
  '- filename: string with extension (e.g., "notes.md", "data.json")',
  "- content: string (for create/rewrite/update)",
  "",
  "**NEVER call artifacts tool without command and filename.**",
  "",
  "Actions:",
  "- create — Create new file. Requires: filename, content",
  "- rewrite — Replace entire file. Requires: filename, content",
  "- update — String replacement. Requires: filename, old_str, new_str",
  "- get — Read file content. Requires: filename",
  "- delete — Delete file. Requires: filename",
  "",
  "## 2. REPL (JavaScript execution in extension context)",
  "",
  "The REPL executes JavaScript inside the extension. Use it for multi-step workflows.",
  "REPL code can call: browserjs(), navigate(), native input functions, artifact functions.",
  "",
  "**CRITICAL — Tool outputs are HIDDEN from the user:**",
  "When you reference data from tool outputs in your response, you MUST repeat the relevant parts.",
  "",
  "## 3. Artifact Functions (code saved in REPL)",
  "",
  "These functions persist JSON data across REPL executions:",
  "- `await createOrUpdateArtifact(name, data)` — Save JSON data",
  "- `await getArtifact(name)` — Retrieve saved data",
  "- `await listArtifacts()` — List all artifact names",
  "- `await deleteArtifact(name)` — Delete an artifact",
  "",
  "Use `returnFile` to deliver generated files to the user:",
  "- `await returnFile(name, content, mimeType)` — Saves to Artifact Panel",
  '  - name: filename with extension (e.g., "page.html", "data.csv")',
  "  - content: string or Uint8Array",
  '  - mimeType: e.g., "text/html", "text/csv", "text/markdown"',
  "",
  "**CRITICAL — Use `returnFile` when:**",
  '  User asks to "generate HTML", "create a report", "export data" → ALWAYS call `returnFile` at the end.',
  "  Do NOT just print HTML/content with console.log.",
  "",
  "## 4. Clear Boundary Summary",
  "",
  "| Task | Use | Do NOT Use |",
  "|------|-----|------------|",
  "| Click elements | `nativeClick()` | `browserjs().click()` |",
  "| Type text | `nativeType()` | `browserjs().value =` |",
  "| Press keys | `nativePress()` | `browserjs()` |",
  "| Read/scrape data | `browserjs()` | — |",
  "| Navigate | `navigate()` | `window.location` |",
  "| Store data | `createOrUpdateArtifact()` | — |",
  "| Generate file for user | `returnFile()` | console.log |",
  "| Check site capabilities | `skills` object | Custom code |",
].join("\n");

export const COMMON_PATTERNS = [
  "# Common Patterns",
  "",
  "## Research & Document",
  "",
  "Extract content from a page and save it as a document:",
  "```javascript",
  "const content = await browserjs(() => ({",
  "  title: document.title,",
  "  text: document.body.innerText.substring(0, 5000),",
  "}));",
  "await returnFile('research.md', `# ${content.title}\\n\\n${content.text}`, 'text/markdown');",
  "```",
  "",
  "## Multi-page Scraping (SPA / CSR sites)",
  "",
  "Collect data across multiple pages that need JS rendering (use `navigate` + `browserjs`):",
  "```javascript",
  "const allItems = [];",
  "for (let page = 1; page <= 5; page++) {",
  "  await navigate(`https://site.com/list?page=${page}`);",
  "  const items = await browserjs(() =>",
  "    Array.from(document.querySelectorAll('.item')).map(el => ({",
  "      name: el.querySelector('h2')?.textContent,",
  "      price: el.querySelector('.price')?.textContent,",
  "    }))",
  "  );",
  "  allItems.push(...items);",
  "}",
  "await createOrUpdateArtifact('items.json', allItems);",
  "```",
  "",
  "<!-- BG_FETCH_SECTION_START -->",
  "## Multi-URL Fetch (static / server-rendered pages, JSON APIs)",
  "",
  "**Prefer this over top-level `bg_fetch` when you have 5+ URLs.** Results never hit the AI context — they go straight to an artifact, saving tokens and turns.",
  "```javascript",
  "const urls = [",
  "  'https://example.com/docs/a', 'https://example.com/docs/b', /* ... */",
  "];",
  "const contents = {};",
  "for (const url of urls) {",
  "  try {",
  "    const { body } = await bgFetch(url, { responseType: 'readability' });",
  "    contents[url] = body.content;",
  "  } catch (e) {",
  "    contents[url] = 'Error: ' + e.message;",
  "  }",
  "}",
  "await createOrUpdateArtifact('docs.json', contents);",
  "return `Collected ${Object.keys(contents).length} pages`;",
  "```",
  "<!-- BG_FETCH_SECTION_END -->",
  "",
  "**Data storage rule:** `createOrUpdateArtifact` for structured JSON data (name with `.json` extension). `returnFile` for user-facing files (HTML, CSV, Markdown, images).",
  "",
  "## Data Processing",
  "",
  "Extract, transform, and save data:",
  "```javascript",
  "// 1. Extract",
  "const raw = await browserjs((sel) =>",
  "  Array.from(document.querySelectorAll(sel)).map(el => ({",
  "    title: el.querySelector('.title')?.textContent?.trim(),",
  "    price: el.querySelector('.price')?.textContent?.trim(),",
  "  })),",
  "'.product'",
  ");",
  "",
  "// 2. Transform",
  "const processed = raw.filter(item => item.title && item.price);",
  "",
  "// 3. Save",
  "const csv = ['name,price', ...processed.map(i => `${i.title},${i.price}`)].join('\\n');",
  "await returnFile('products.csv', csv, 'text/csv');",
  "```",
  "",
  "## Interactive Dashboard",
  "",
  "Generate an HTML dashboard from scraped data:",
  "```javascript",
  "const data = await getArtifact('items');",
  "const rows = data.map(i => `<tr><td>${i.name}</td><td>${i.price}</td></tr>`).join('');",
  "const html = `<!DOCTYPE html>",
  "<html><head><title>Dashboard</title></head>",
  "<body><table><thead><tr><th>Name</th><th>Price</th></tr></thead>",
  "<tbody>${rows}</tbody></table></body></html>`;",
  "await returnFile('dashboard.html', html, 'text/html');",
  "```",
  "",
  "## Website Automation",
  "",
  "Fill forms and navigate workflows:",
  "```javascript",
  "// Login flow",
  "await navigate('https://site.com/login');",
  "await nativeType('input[name=\"email\"]', 'user@example.com');",
  "await nativeType('input[name=\"password\"]', 'secret');",
  "await nativeClick('button[type=\"submit\"]');",
  "",
  "// Wait for redirect",
  "let attempts = 0;",
  "while (attempts < 10) {",
  "  const onDashboard = await browserjs(() => location.pathname.includes('/dashboard'));",
  "  if (onDashboard) break;",
  "  await new Promise(r => setTimeout(r, 500));",
  "  attempts++;",
  "}",
  "```",
  "",
  "## Form Submission That Doesn't Work",
  "",
  "If clicking the submit button doesn't submit the form:",
  "1. Check if all required fields are filled",
  "2. Try pressing Enter after the last field: `await nativePress('Enter')`",
  "3. Some forms need explicit button click: `await nativeClick('button[type=\"submit\"]')`",
  "",
  "## Waiting for Page Updates",
  "",
  "After clicking or typing, the page might update dynamically. Use browserjs() to poll for changes:",
  "```javascript",
  "let attempts = 0;",
  "while (attempts < 10) {",
  "  const exists = await browserjs((sel) => document.querySelector(sel) !== null, '.result');",
  "  if (exists) break;",
  "  await new Promise(r => setTimeout(r, 500));",
  "  attempts++;",
  "}",
  "```",
  "",
  "## Element Not Found",
  "",
  'If nativeClick() or nativeType() fails with "Element not found":',
  "1. Use browserjs() to verify the selector",
  "2. Try alternative selectors (class, ID, attribute)",
  "3. If inside an iframe, you cannot access it — tell the user",
  "4. If lazy-loaded, scroll first with nativeScroll()",
].join("\n");

export const AVAILABLE_FUNCTIONS = [
  "# Available Functions",
  "",
  "## REPL Persistence Model (read this first)",
  "",
  "- Variables declared in one `repl` call do **NOT** survive to the next call. Each call starts from a fresh scope.",
  "- For multi-step workflows, save intermediate state via `createOrUpdateArtifact(name, data)` and read it back with `getArtifact(name)` in a later call.",
  "- Anti-pattern: calling `repl` multiple times merely to re-verify or re-inspect data you already retrieved. Previous tool results remain visible to you at full length in the conversation history — trust them.",
  "",
  "## Skills (Check First)",
  "",
  "Before writing custom code, check if a skill is available for the current site.",
  "",
  "### When to Use",
  "- A skill matches the current domain",
  "- The skill has an extractor for the data you need",
  "- You want tested, reliable code",
  "",
  "### How to Use",
  "```javascript",
  "// Check available skills",
  "console.log(Object.keys(skills));",
  "",
  "// Use skill extractor in browserjs()",
  'const code = skills["youtube"].extractors["videoInfo"].code;',
  "const fn = new Function(`return (${code})`)();",
  "const info = await browserjs(fn);",
  "```",
  "",
  "### Do NOT Write Custom Code When",
  "- A skill already exists for the site",
  "- The skill covers the functionality you need",
  "",
  "## Native Input Functions (REQUIRED for interactions)",
  "",
  "Dispatch trusted browser events (isTrusted: true) that work reliably on all sites.",
  "",
  "### When to Use",
  "- **ALWAYS** for clicking elements (buttons, links, checkboxes)",
  "- **ALWAYS** for typing text into inputs and textareas",
  "- **ALWAYS** for pressing keys (Enter, Tab, Escape, etc.)",
  "- **ALWAYS** for form submissions",
  "",
  "### Do NOT Use browserjs() For",
  "- Clicking elements — use nativeClick()",
  "- Typing text — use nativeType()",
  "- Pressing keys — use nativePress()",
  "- Form submissions — use nativeClick() on the submit button",
  "",
  "### Mouse Actions",
  "- `await nativeClick(selector, options?)` — Click an element",
  '  - options: { button?: "left" | "right" | "middle", offsetX?: number, offsetY?: number }',
  "- `await nativeDoubleClick(selector)` — Double-click an element",
  "- `await nativeRightClick(selector)` — Right-click (context menu)",
  "- `await nativeHover(selector)` — Move mouse over element",
  "",
  "### Keyboard Actions",
  "- `await nativeType(selector, text)` — Type text into an input/textarea",
  "- `await nativePress(key)` — Press and release a key (Enter, Tab, Escape, ArrowUp, etc.)",
  "- `await nativeKeyDown(key)` — Hold a key down (for modifier combinations)",
  "- `await nativeKeyUp(key)` — Release a held key",
  "",
  "### Focus Actions",
  "- `await nativeFocus(selector)` — Focus an element without clicking",
  "- `await nativeBlur(selector?)` — Remove focus (uses activeElement if selector omitted)",
  "",
  "### Scroll & Selection",
  "- `await nativeScroll(selector, options?)` — Scroll element into view",
  '  - options: { behavior?: "auto" | "smooth", block?: "start" | "center" | "end" | "nearest" }',
  "- `await nativeSelectText(selector, start?, end?)` — Select text",
  "  - Omit start/end to select all text",
  "",
  "### Examples",
  "```javascript",
  "// ✅ CORRECT: Form submission with native functions",
  "await nativeType('input[name=\"username\"]', 'john_doe');",
  "await nativeType('input[name=\"password\"]', 'secret123');",
  "await nativeClick('button[type=\"submit\"]');",
  "",
  "// ❌ WRONG: Using browserjs for interactions",
  "await browserjs(() => {",
  "  document.querySelector('input[name=\"username\"]').value = 'john_doe';",
  "  document.querySelector('button[type=\"submit\"]').click();",
  "});",
  "",
  "// ✅ CORRECT: Keyboard shortcuts",
  "await nativeKeyDown('Control');",
  "await nativePress('a');  // Select all",
  "await nativeKeyUp('Control');",
  "```",
  "",
  "## browserjs(fn, ...args) — For Data Extraction ONLY",
  "",
  "Execute JavaScript in the active tab's page context to read/scrape data.",
  "",
  "### When to Use",
  "- Extracting text content from elements",
  "- Getting page metadata (title, URL)",
  "- Checking element existence or visibility",
  "- Reading computed styles",
  "- Polling for dynamic content",
  "",
  "### Critical — Function Serialization",
  "The function is **serialized** and executed in the page context:",
  "",
  "- ✅ MUST pass data as parameters (JSON-serializable only)",
  "- ✅ CAN use artifact functions (auto-injected)",
  "- ❌ CANNOT access variables from REPL scope (closures don't work)",
  "- ❌ CANNOT navigate — no window.location inside browserjs()",
  "",
  "### Examples",
  "```javascript",
  "// ✅ Get page title",
  "const title = await browserjs(() => document.title);",
  "",
  "// ✅ Extract data with parameters (CORRECT)",
  "const selector = '.product';",
  "const products = await browserjs((sel) => {",
  "  return Array.from(document.querySelectorAll(sel)).map(el => ({",
  "    name: el.querySelector('h2')?.textContent,",
  "    price: el.querySelector('.price')?.textContent,",
  "  }));",
  "}, selector);  // Pass as parameter",
  "",
  "// ❌ Closure trap (WRONG)",
  "const selector = '.product';",
  "await browserjs(() => {",
  "  // selector is undefined here!",
  "  return document.querySelectorAll(selector).length;",
  "});",
  "```",
  "",
  "## navigate(url)",
  "",
  "Navigate to a URL and wait for page load.",
  "",
  "### When to Use",
  "- Inside a `repl` loop to move across multiple pages (SPA/CSR sites that need JS rendering), combined with `browserjs()` for extraction and `createOrUpdateArtifact()` for storage",
  "- Navigating to a different URL as a one-off step",
  "",
  "### Do NOT Use For",
  "- Single page interactions (use native functions)",
  "- Inside browserjs() (closures don't work)",
  "- Top-level multi-URL collection loops — drive the loop from a single `repl` call instead",
  "<!-- BG_FETCH_SECTION_START -->",
  "- Multi-URL fetching of static / server-rendered pages — use `bgFetch` instead",
  "<!-- BG_FETCH_SECTION_END -->",
  "",
  "```javascript",
  "// ✅ Navigate and extract",
  "await navigate('https://example.com');",
  "const title = await browserjs(() => document.title);",
  "```",
  "",
  "<!-- BG_FETCH_SECTION_START -->",
  "## bgFetch(url, options?) — Multi-URL fetch that bypasses the AI context",
  "",
  "Fetch an external URL via the background service worker. CORS-free, does not touch the active tab, and — unlike top-level `bg_fetch` — results never hit the AI conversation history, so you can save them straight into an artifact.",
  "",
  "### When to Use",
  "- **5+ URLs** fetched in a single `repl` call (loop them)",
  "- Writing the response body directly to `createOrUpdateArtifact()`",
  "- JSON APIs, GitHub raw files, static documentation pages",
  "",
  "### Do NOT Use For",
  "- 1〜2 URLs whose contents you want to read inline — use top-level `bg_fetch`",
  "- SPA/CSR sites whose content is JS-rendered — use `navigate()` + `browserjs()`",
  "",
  "Shares the `enableBgFetch` settings toggle with the top-level `bg_fetch` tool; if that tool is disabled by the user, `bgFetch` is also blocked (error: `bgFetch is disabled in settings`).",
  "",
  "### Signature",
  "```ts",
  "bgFetch(url: string, options?: {",
  '  method?: "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "HEAD" | "OPTIONS",',
  "  headers?: Record<string, string>,",
  "  body?: string,",
  '  responseType?: "text" | "json" | "base64" | "readability",  // default: "text"',
  "  timeout?: number,  // ms, default 30000, max 60000",
  "}): Promise<{",
  "  url: string, ok: boolean, status: number, statusText: string,",
  "  headers: Record<string, string>, body: string | object,",
  "  redirected?: boolean, redirectUrl?: string,",
  "}>",
  "```",
  "",
  "```javascript",
  "// ✅ Collect 20 docs pages in one repl call → artifact",
  "const contents = {};",
  "for (const url of urls) {",
  "  try {",
  "    const { body } = await bgFetch(url, { responseType: 'readability' });",
  "    contents[url] = body.content;",
  "  } catch (e) {",
  "    contents[url] = 'Error: ' + e.message;",
  "  }",
  "}",
  "await createOrUpdateArtifact('docs.json', contents);",
  "return `Collected ${Object.keys(contents).length} pages`;",
  "```",
  "<!-- BG_FETCH_SECTION_END -->",
  "",
  "## Artifact Functions (Data Persistence)",
  "",
  "Store and retrieve JSON data across REPL executions:",
  "",
  "- `await createOrUpdateArtifact(name, data)` — Save JSON data",
  "- `await getArtifact(name)` — Retrieve saved data",
  "- `await listArtifacts()` — List all artifact names",
  "- `await deleteArtifact(name)` — Delete an artifact",
  "",
  "```javascript",
  "// Save scraping results",
  "await createOrUpdateArtifact('products', [{ name: 'A' }, { name: 'B' }]);",
  "",
  "// Retrieve in another script",
  "const products = await getArtifact('products');",
  "```",
  "",
  "## File Functions",
  "",
  "**IMPORTANT: Use `returnFile` to deliver generated files (HTML, CSV, Markdown, images, etc.) to the user.**",
  "Files saved with `returnFile` are displayed in the Artifact Panel — this is the ONLY way to show generated content.",
  "",
  "- `await returnFile(name, content, mimeType)`",
  '  - name: filename with extension (e.g., "page.html", "data.csv", "report.md")',
  "  - content: string or Uint8Array",
  '  - mimeType: e.g., "text/html", "text/csv", "text/markdown"',
  "",
  "```javascript",
  "// Generate HTML and deliver it to the user",
  "const html = '<!DOCTYPE html>\\n<html>...</html>';",
  "await returnFile('page.html', html, 'text/html');",
  "",
  "// Generate CSV",
  "const csv = 'name,price\\nA,100\\nB,200';",
  "await returnFile('products.csv', csv, 'text/csv');",
  "```",
  "",
  "## Skill Draft Management",
  "",
  "Skill 下書きを管理するツール群。ユーザーが Settings で承認するまで custom skill には反映されない。",
  "",
  "### ワークフロー",
  "1. `create_skill_draft` — 新しい下書きを作成",
  "2. `list_skill_drafts` — 承認待ちの下書き一覧と draftId を取得",
  "3. `update_skill_draft` — 既存の下書きを改善・修正（draftId 指定）",
  "4. `delete_skill_draft` — 不要な下書きを破棄（draftId 指定）",
  "",
  "### list_skill_drafts",
  "承認待ちの下書き一覧を取得する。各下書きの draftId、名前、バリデーション状態、suggestedFixes を返す。",
  "",
  "### create_skill_draft",
  "新しい Skill の下書きを作成する。validation 結果を返し、Settings で承認後に custom skill に反映。",
  "",
  "### update_skill_draft",
  "draftId で指定した下書きを部分更新する。更新後に再 validation が実行される。",
  "- matchers: フィールド単位でマージ（hosts のみ指定すると paths は既存値を維持）",
  "- extractors: 指定時は全置換",
  "",
  "### delete_skill_draft",
  "draftId で指定した下書きを削除する。validation reject の下書きを捨てて作り直したい場合に使う。",
  "",
  "## Artifacts Tool (YOU Author Content)",
  "",
  "**CRITICAL — Required Parameters:**",
  '- command: "create" | "rewrite" | "update" | "get" | "delete"',
  "- filename: string with extension",
  "- content: string (for create/rewrite/update)",
  "",
  "| Action | Description | Required Fields |",
  "|--------|-------------|----------------|",
  "| create | Create new file | filename, content |",
  "| rewrite | Replace entire file | filename, content |",
  "| update | String replacement | filename, old_str, new_str |",
  "| get | Read file content | filename |",
  "| delete | Delete file | filename |",
].join("\n");

export type ReplDescriptionSectionKey =
  | "TOOL_PHILOSOPHY"
  | "COMMON_PATTERNS"
  | "AVAILABLE_FUNCTIONS";

const SECTIONS: Record<ReplDescriptionSectionKey, string> = {
  TOOL_PHILOSOPHY,
  COMMON_PATTERNS,
  AVAILABLE_FUNCTIONS,
};

// bgFetch 関連の部分は <!-- BG_FETCH_SECTION_START --> / <!-- BG_FETCH_SECTION_END -->
// で囲んである。enableBgFetch=false の時はマーカごと中身を削除し、AI から
// bgFetch の存在を隠す。true の時はマーカ行だけ取り除いて中身を残す。
//
// 同じマーカは system-prompt-v2 経由の prompt でも使われるため、本ヘルパは
// 両パスから再利用する。どちらの値でも sentinel 文字列自体は必ず取り除く。
const BG_FETCH_SECTION_RE = /^<!-- BG_FETCH_SECTION_START -->\n([\s\S]*?)^<!-- BG_FETCH_SECTION_END -->\n?/gm;

export function stripBgFetchSections(text: string, enableBgFetch: boolean): string {
  if (enableBgFetch) {
    return text.replace(BG_FETCH_SECTION_RE, (_match, body: string) => body);
  }
  return text.replace(BG_FETCH_SECTION_RE, "");
}

export function assembleReplDescriptionSections(
  keys: ReplDescriptionSectionKey[],
  options: { enableBgFetch?: boolean } = {},
): string {
  const joined = keys.map((key) => SECTIONS[key]).join("\n\n");
  return stripBgFetchSections(joined, options.enableBgFetch ?? true);
}
