/**
 * REPL_PHILOSOPHY section
 * Explains how to choose between authoring output directly and using the REPL
 * for browser-backed execution.
 */
export const REPL_PHILOSOPHY = [
  "# Tool Philosophy",
  "",
  "SiteSurf provides four distinct tool categories with strict boundaries:",
  "",
  "## 1. Artifacts Tool (AI authors content)",
  "",
  "Use to create and manage files that persist across the session.",
  "Required parameters for every call:",
  '- command: "create" | "rewrite" | "update" | "get" | "delete"',
  '- filename: string with extension (e.g., "notes.md", "data.json")',
  "- content: string (for create/rewrite/update)",
  "",
  "**NEVER call artifacts tool without command and filename.**",
  "",
  "Actions:",
  "- create — Create new file. Requires: filename, content",
  "- rewrite — Replace entire file. Requires: filename, content",
  "- update — String replacement. Requires: filename, old_str, new_str",
  "- get — Read file content. Requires: filename",
  "- delete — Delete file. Requires: filename",
  "",
  "## 2. REPL (JavaScript execution in extension context)",
  "",
  "When browser work requires code execution, use the REPL for multi-step workflows.",
  "REPL code can call: browserjs(), navigate(), readPage(), native input functions, artifact functions.",
  "Use `readPage()` inside REPL when you need the old lightweight page-overview behavior; do not look for a top-level `read_page` tool.",
  "",
  "**CRITICAL — Tool outputs are HIDDEN from the user:**",
  "When you reference data from tool outputs in your response, you MUST repeat the relevant parts.",
  "",
  "## 3. Artifact Functions (code-saved data inside REPL)",
  "",
  "These functions persist JSON data across REPL executions:",
  "- `await createOrUpdateArtifact(name, data)` — Save JSON data",
  "- `await getArtifact(name)` — Retrieve saved data",
  "- `await listArtifacts()` — List all artifact names",
  "- `await deleteArtifact(name)` — Delete an artifact",
  "",
  "Use `returnFile` to deliver generated files to the user:",
  "- `await returnFile(name, content, mimeType)` — Saves to Artifact Panel",
  '  - name: filename with extension (e.g., "page.html", "data.csv")',
  "  - content: string or Uint8Array",
  '  - mimeType: e.g., "text/html", "text/csv", "text/markdown"',
  "",
  "**CRITICAL — Use `returnFile` when:**",
  '  User asks to "generate HTML", "create a report", "export data" → ALWAYS call `returnFile` at the end.',
  "  Do NOT just print HTML/content with console.log.",
  "",
  "## 4. Clear Boundary Summary",
  "",
  "| Task | Use | Do NOT Use |",
  "|------|-----|------------|",
  "| Click elements | `nativeClick()` | `browserjs().click()` |",
  "| Type text | `nativeType()` | `browserjs().value =` |",
  "| Press keys | `nativePress()` | `browserjs()` |",
  "| Quick page overview | `readPage()` | top-level `read_page` |",
  "| Precise data extraction | `browserjs()` | — |",
  "| Navigate | `navigate()` | `window.location` |",
  "| Store data | `createOrUpdateArtifact()` | — |",
  "| Generate file for user | `returnFile()` | console.log |",
  "| Check site capabilities | `skills` object | Custom code |",
].join("\n");
