export const AVAILABLE_FUNCTIONS = [
  "# Available Functions",
  "",
  "## REPL Persistence Model (read this first)",
  "",
  "- Variables declared in one `repl` call do **NOT** survive to the next call. Each call starts from a fresh scope.",
  "- For multi-step workflows, save intermediate state via `saveArtifact(name, data)` and read it back with `getArtifact(name)` in a later call.",
  "- Anti-pattern: calling `repl` multiple times merely to re-verify or re-inspect data you already retrieved. Previous tool results remain visible to you at full length in the conversation history — trust them.",
  "",
  "## Skills (Check First)",
  "",
  "Check `skills` before writing custom DOM code. If a site skill already covers the workflow, use it instead of re-implementing extraction or interaction logic.",
  "",
  "```javascript",
  "const info = await browserjs(() => window.youtube.getVideoInfo());",
  "```",
  "",
  "## Quick Page Read",
  "",
  "- `readPage(maxDepth?)` — Get the current page's lightweight overview (`text` + `simplifiedDom`) using the same extraction path as BrowserExecutor.readPageContent(). Use this first when you need a quick page read before precise `browserjs()` extraction.",
  "",
  "## Native Input Functions (REQUIRED for interactions)",
  "",
  "Chrome debugger 経由で trusted な入力イベントを発火する。通常 DOM 操作で動かない bot 対策ページではこれを使う。",
  "",
  "- `nativeClick(selector, options?)`",
  "- `nativeDoubleClick(selector)`",
  "- `nativeRightClick(selector)`",
  "- `nativeHover(selector)`",
  "- `nativeType(selector, text)`",
  "- `nativePress(key)`",
  "- `nativeKeyDown(key)`",
  "- `nativeKeyUp(key)`",
  "- `nativeFocus(selector)`",
  "- `nativeBlur(selector?)`",
  "- `nativeScroll(selector, options?)`",
  "- `nativeSelectText(selector, start?, end?)`",
  "",
  "## Function Summary",
  "",
  "| Function | Purpose |",
  "| --- | --- |",
  "| `browserjs(fn, ...args)` | Read/scrape JSON-serializable data from the active page context. |",
  "| `navigate(url)` | Navigate to another page and wait for load before the next extraction step. |",
  "| `readPage(maxDepth?)` | Read the current page's lightweight overview (`text` + `simplifiedDom`) without leaving REPL. |",
  "<!-- BG_FETCH_SECTION_START -->",
  "| `bgFetch(url, options?)` | Fetch static/server-rendered pages or APIs outside the page context. 詳しい使い分けは top-level `bg_fetch` tool description を参照。 |",
  "<!-- BG_FETCH_SECTION_END -->",
  "| `saveArtifact(name, data, options?)` | Save JSON/text/binary. `Uint8Array` or (string + extension/`mimeType`) → file; otherwise → JSON. `options.visible: false` keeps it out of the UI. |",
  '| `getArtifact(name)` | Returns `{ kind: "json", data }` or `{ kind: "file", bytes, mimeType }`. |',
  "| `listArtifacts()` | Returns `ArtifactMeta[]` — `[{ name, kind, mimeType?, size, visible, createdAt, updatedAt }]`. |",
  "| `deleteArtifact(name)` | Delete an artifact (any kind). |",
  "",
  // NOTE: skill-draft ツールと artifacts ツールの詳細は各 top-level ツールの
  // description に保持する。ここ（AVAILABLE_FUNCTIONS）は REPL 内から使える
  // 関数に限定して重複を避ける。
].join("\n");
