export const COMMON_PATTERNS = [
  "# Common Patterns",
  "",
  "## Research & Document",
  "",
  "Extract content from a page and save it as a document:",
  "```javascript",
  "const content = await browserjs(() => ({",
  "  title: document.title,",
  "  text: document.body.innerText.substring(0, 5000),",
  "}));",
  "await saveArtifact('research.md', `# ${content.title}\\n\\n${content.text}`);",
  "```",
  "",
  "## Multi-page Scraping (SPA / CSR sites)",
  "",
  "Collect data across multiple pages that need JS rendering (use `navigate` + `browserjs`):",
  "```javascript",
  "const allItems = [];",
  "for (let page = 1; page <= 5; page++) {",
  "  await navigate(`https://site.com/list?page=${page}`);",
  "  const items = await browserjs(() =>",
  "    Array.from(document.querySelectorAll('.item')).map(el => ({",
  "      name: el.querySelector('h2')?.textContent,",
  "      price: el.querySelector('.price')?.textContent,",
  "    }))",
  "  );",
  "  allItems.push(...items);",
  "}",
  "await saveArtifact('items.json', allItems);",
  "```",
  "",
  "**Data storage rule:** `saveArtifact(name, data)` handles all kinds. Pass an object/array → JSON; pass a string with a file extension (or explicit `mimeType`) → user-facing file (HTML, CSV, Markdown, images). Pass `Uint8Array` for binary. Use `{ visible: false }` for internal scratch data that should not show in the Artifact Panel.",
  "",
  "## Data Processing",
  "",
  "Extract, transform, and save data:",
  "```javascript",
  "// 1. Extract",
  "const raw = await browserjs((sel) =>",
  "  Array.from(document.querySelectorAll(sel)).map(el => ({",
  "    title: el.querySelector('.title')?.textContent?.trim(),",
  "    price: el.querySelector('.price')?.textContent?.trim(),",
  "  })),",
  "'.product'",
  ");",
  "",
  "// 2. Transform",
  "const processed = raw.filter(item => item.title && item.price);",
  "",
  "// 3. Save",
  "const csv = ['name,price', ...processed.map(i => `${i.title},${i.price}`)].join('\\n');",
  "await saveArtifact('products.csv', csv);",
  "```",
  "",
  "## Interactive Dashboard",
  "",
  "Generate an HTML dashboard from scraped data:",
  "```javascript",
  "const { data } = await getArtifact('items.json');",
  "const rows = data.map(i => `<tr><td>${i.name}</td><td>${i.price}</td></tr>`).join('');",
  "const html = `<!DOCTYPE html>",
  "<html><head><title>Dashboard</title></head>",
  "<body><table><thead><tr><th>Name</th><th>Price</th></tr></thead>",
  "<tbody>${rows}</tbody></table></body></html>`;",
  "await saveArtifact('dashboard.html', html);",
  "```",
  "",
  "## Website Automation",
  "",
  "Fill forms and navigate workflows:",
  "```javascript",
  "// Login flow",
  "await navigate('https://site.com/login');",
  "await nativeType('input[name=\"email\"]', 'user@example.com');",
  "await nativeType('input[name=\"password\"]', 'secret');",
  "await nativeClick('button[type=\"submit\"]');",
  "",
  "// Wait for redirect",
  "let attempts = 0;",
  "while (attempts < 10) {",
  "  const onDashboard = await browserjs(() => location.pathname.includes('/dashboard'));",
  "  if (onDashboard) break;",
  "  await new Promise(r => setTimeout(r, 500));",
  "  attempts++;",
  "}",
  "```",
  "",
  "## Form Submission That Doesn't Work",
  "",
  "If clicking the submit button doesn't submit the form:",
  "1. Check if all required fields are filled",
  "2. Try pressing Enter after the last field: `await nativePress('Enter')`",
  "3. Some forms need explicit button click: `await nativeClick('button[type=\"submit\"]')`",
  "",
  "## Waiting for Page Updates",
  "",
  "After clicking or typing, the page might update dynamically. Use browserjs() to poll for changes:",
  "```javascript",
  "let attempts = 0;",
  "while (attempts < 10) {",
  "  const exists = await browserjs((sel) => document.querySelector(sel) !== null, '.result');",
  "  if (exists) break;",
  "  await new Promise(r => setTimeout(r, 500));",
  "  attempts++;",
  "}",
  "```",
  "",
  "## Element Not Found",
  "",
  'If nativeClick() or nativeType() fails with "Element not found":',
  "1. Use browserjs() to verify the selector",
  "2. Try alternative selectors (class, ID, attribute)",
  "3. If inside an iframe, you cannot access it — tell the user",
  "4. If lazy-loaded, scroll first with nativeScroll()",
].join("\n");
