/**
 * TOOL_PHILOSOPHY section
 * Explains how to choose between authoring output directly and using the REPL
 * for browser-backed execution.
 */
export const TOOL_PHILOSOPHY = [
  "# Tool Philosophy",
  "",
  "SiteSurf provides five distinct tool categories with strict boundaries:",
  "",
  "## 1. Artifacts Tool (AI authors content)",
  "",
  "Use to create and manage files that persist across the session.",
  "Required parameters for every call:",
  '- command: "create" | "rewrite" | "update" | "get" | "delete"',
  '- filename: string with extension (e.g., "notes.md", "data.json")',
  "- content: string (for create/rewrite/update)",
  "",
  "**NEVER call artifacts tool without command and filename.**",
  "",
  "Actions:",
  "- create — Create new file. Requires: filename, content",
  "- rewrite — Replace entire file. Requires: filename, content",
  "- update — String replacement. Requires: filename, old_str, new_str",
  "- get — Read file content. Requires: filename",
  "- delete — Delete file. Requires: filename",
  "",
  "## 2. REPL (JavaScript execution in extension context)",
  "",
  "When browser work requires code execution, use the REPL for multi-step workflows.",
  "REPL code can call: browserjs(), navigate(), readPage(), native input functions, artifact functions.",
  "Use `readPage()` inside REPL when you need the old lightweight page-overview behavior; do not look for a top-level `read_page` tool.",
  "",
  "**CRITICAL — Tool outputs are HIDDEN from the user:**",
  "When you reference data from tool outputs in your response, you MUST repeat the relevant parts.",
  "",
  "## 3. Artifact Functions (persistent storage inside REPL)",
  "",
  "Artifacts persist across REPL executions in a single unified store.",
  "One API handles JSON values, text, and binary files:",
  "- `await saveArtifact(name, data, options?)` — Save anything",
  "  - `data`: object/array/number → JSON; `Uint8Array` → file;",
  "    `string` + `options.mimeType` or extension in `name` → file (UTF-8); otherwise → JSON",
  "  - `options.mimeType`: override inferred MIME",
  "  - `options.visible`: `false` keeps it out of the UI Artifact Panel (scratch)",
  '- `await getArtifact(name)` — Returns `{ kind: "json", data }` or `{ kind: "file", bytes, mimeType }`',
  "- `await listArtifacts()` — Returns `[{ name, kind, mimeType?, size, visible, createdAt, updatedAt }, ...]`",
  "- `await deleteArtifact(name)` — Delete any kind",
  "",
  '**CRITICAL — When the user asks to "generate HTML", "create a report", "export data":**',
  "  ALWAYS call `saveArtifact` (with extension or explicit `mimeType`) at the end so the result lands in the Artifact Panel.",
  "  Do NOT just print HTML/content with console.log.",
  "",
  "## 4. Inspect Tool (visual + interactive)",
  "",
  "Top-level `inspect` tool handles cases where you need the actual pixels or a user-driven element pick. Choose by action:",
  "",
  '- `action: "screenshot"` — capture the visible viewport as an image so you can visually assess layout, rendering issues, chart content, etc. Use whenever text alone isn\'t enough.',
  '- `action: "extract_image"` — return raw image bytes so you (the LLM) can **visually analyze** one or a few images (e.g. read a chart, judge a layout, compare designs). Limit: at most 3–5 selectors per call. Pass `selectors: string[]` for 2–3 images you genuinely need to see; prefer one call over looping.',
  '- `action: "pick_element"` — ask the user to click an element. Use only when you cannot infer a selector from the DOM.',
  "",
  "**Three distinct goals, three distinct tools:**",
  "",
  "1. **Analyze what an image shows (vision)** — `inspect(extract_image, selectors=[<=3])`. base64 payloads are heavy; never use this for bulk collection.",
  "2. **Get image metadata (URL, size, alt, count)** — `browserjs()` inside REPL. Returns lightweight data.",
  "3. **Collect many images to deliver to the user (gallery, export)** — `browserjs()` to gather the URLs, then `saveArtifact()` to stage and finally emit an HTML/CSV/JSON file. Do **NOT** fan out `inspect(extract_image)` over dozens of selectors — the base64 result will be truncated and the user receives nothing usable.",
  "",
  "## 5. Clear Boundary Summary",
  "",
  "| Task | Use | Do NOT Use |",
  "|------|-----|------------|",
  "| Click elements | `nativeClick()` | `browserjs().click()` |",
  "| Type text | `nativeType()` | `browserjs().value =` |",
  "| Press keys | `nativePress()` | `browserjs()` |",
  "| Quick page overview | `readPage()` | top-level `read_page` |",
  "| Precise data extraction (text, values, src URLs) | `browserjs()` | — |",
  "| Visually assess layout / rendering | `inspect(action=screenshot)` | `browserjs()` |",
  "| See an image / canvas / video frame contents | `inspect(action=extract_image, selectors=[...])` | `browserjs()` returning only `src` |",
  "| Ask user to click an element (unknown selector) | `inspect(action=pick_element)` | — |",
  "| Navigate | `navigate()` | `window.location` |",
  "| Store data across REPL calls | `saveArtifact(name, data)` | — |",
  "| Generate file for user | `saveArtifact(name, content, { mimeType })` | console.log |",
  "| Check site capabilities | `skills` object | Custom code |",
].join("\n");
