#!/usr/bin/env npx tsx

import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT = join(__dirname, "..", "src", "shared", "models.generated.ts");

interface ModelsDevModel {
  id: string;
  name: string;
  tool_call?: boolean;
  reasoning?: boolean;
  limit?: { context?: number; output?: number };
}

interface ProviderModels {
  defaultModel: string;
  models: Array<{ id: string; name: string; reasoning: boolean }>;
}

const PROVIDER_MAP: Record<string, { key: string; defaultModel: string }> = {
  anthropic: { key: "anthropic", defaultModel: "claude-sonnet-4-6" },
  openai: { key: "openai", defaultModel: "gpt-5.4" },
  google: { key: "google", defaultModel: "gemini-2.5-flash" },
  "github-copilot": { key: "copilot", defaultModel: "gpt-4.1" },
  "kimi-for-coding": { key: "kimi-coding", defaultModel: "k2p5" },
  zai: { key: "zai", defaultModel: "glm-5.1" },
  "zai-coding-plan": { key: "zai-coding", defaultModel: "glm-5.1" },
};

const SKIP_PATTERNS = [
  /^text-embedding/,
  /^dall-e/,
  /^whisper/,
  /^tts/,
  /^gemma/,
  /^gemini-.*embedding/,
  /^gpt-image/,
  /codex/i,
  /-preview-\d/,
];

function shouldSkip(id: string): boolean {
  return SKIP_PATTERNS.some((p) => p.test(id));
}

async function main() {
  console.log("Fetching models from models.dev/api.json ...");
  const res = await fetch("https://models.dev/api.json");
  if (!res.ok) throw new Error(`Failed to fetch: ${res.status}`);
  const data = await res.json();

  const result: Record<string, ProviderModels> = {};

  for (const [apiProvider, config] of Object.entries(PROVIDER_MAP)) {
    const providerData = data[apiProvider];
    if (!providerData?.models) {
      console.warn(`No models found for ${apiProvider}`);
      result[config.key] = { defaultModel: config.defaultModel, models: [] };
      continue;
    }

    const models: ProviderModels["models"] = [];

    for (const [modelId, model] of Object.entries(providerData.models)) {
      const m = model as ModelsDevModel;
      if (!m.tool_call) continue;
      if (shouldSkip(modelId)) continue;

      models.push({
        id: modelId,
        name: m.name || modelId,
        reasoning: m.reasoning === true,
      });
    }

    models.sort((a, b) => {
      if (a.reasoning !== b.reasoning) return a.reasoning ? 1 : -1;
      return a.id.localeCompare(b.id);
    });

    result[config.key] = { defaultModel: config.defaultModel, models };
    console.log(`  ${config.key}: ${models.length} models`);
  }

  const output = `// Auto-generated by scripts/generate-models.ts
// Do not edit manually — run 'npx tsx scripts/generate-models.ts' to update
// Source: https://models.dev/api.json

export interface ModelInfo {
  id: string;
  name: string;
  reasoning: boolean;
}

export interface ProviderModels {
  defaultModel: string;
  models: ModelInfo[];
}

export const GENERATED_MODELS: Record<string, ProviderModels> = ${JSON.stringify(result, null, 2)} as const;
`;

  writeFileSync(OUTPUT, output, "utf-8");
  console.log(`\nGenerated ${OUTPUT}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
